package org.keycloak.representations.admin.v2;

import java.util.Set;

import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.hibernate.validator.constraints.URL;
import org.keycloak.representations.admin.v2.validation.PatchClient;
import org.keycloak.representations.admin.v2.validation.ProtocolUnmodified;
import org.keycloak.representations.admin.v2.validation.PutClient;
import org.keycloak.representations.admin.v2.validation.UuidUnmodified;
import org.keycloak.representations.admin.v2.validation.ValidRedirectUris;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import jakarta.validation.constraints.NotBlank;

@Schema(description = "Base client representation with common properties for all client types")
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.EXISTING_PROPERTY,
    property = BaseClientRepresentation.DISCRIMINATOR_FIELD
)
@JsonSubTypes({
    @JsonSubTypes.Type(value = OIDCClientRepresentation.class, name = OIDCClientRepresentation.PROTOCOL),
    @JsonSubTypes.Type(value = SAMLClientRepresentation.class, name = SAMLClientRepresentation.PROTOCOL)
})
@UuidUnmodified(groups = {PutClient.class, PatchClient.class})
@ProtocolUnmodified(groups = {PutClient.class, PatchClient.class})
@ValidRedirectUris
public abstract class BaseClientRepresentation extends BaseRepresentation implements RepresentationWithUuid {
    public static final String APP_URL_FIELD = "appUrl";
    public static final String ENABLED_FIELD = "enabled";
    public static final String DESCRIPTION_FIELD = "description";
    public static final String DISPLAY_NAME_FIELD = "displayName";
    public static final String CLIENT_ID_FIELD = "clientId";
    public static final String UUID_FIELD = "uuid";
    public static final String REDIRECT_URIS_FIELD = "redirectUris";
    public static final String ROLES_FIELD = "roles";

    public static final String DISCRIMINATOR_FIELD = "protocol";

    @JsonIgnore
    protected FieldMapper mapper;

    public BaseClientRepresentation() {
        this(new MapFieldMapper());
    }

    protected BaseClientRepresentation(FieldMapper fields) {
        this.mapper = fields;
    }

    public FieldMapper getFieldMapper() {
        return mapper;
    }

    @JsonPropertyDescription("UUID generated by the server")
    @Schema(description = "UUID generated by the server", readOnly = true)
    @Override
    public String getUuid() {
        return mapper.get(UUID_FIELD);
    }

    public void setUuid(String uuid) {
        this.mapper.set(UUID_FIELD, uuid);
    }

    @NotBlank
    @JsonPropertyDescription("ID uniquely identifying this client")
    public String getClientId() {
        return this.mapper.get(CLIENT_ID_FIELD);
    }

    public void setClientId(String clientId) {
        this.mapper.set(CLIENT_ID_FIELD, clientId);
    }

    @JsonPropertyDescription("Human readable name of the client")
    public String getDisplayName() {
        return this.mapper.get(DISPLAY_NAME_FIELD);
    }

    public void setDisplayName(String displayName) {
        this.mapper.set(DISPLAY_NAME_FIELD, displayName);
    }

    @JsonPropertyDescription("Human readable description of the client")
    public String getDescription() {
        return this.mapper.get(DESCRIPTION_FIELD);
    }

    public void setDescription(String description) {
        this.mapper.set(DESCRIPTION_FIELD, description);
    }

    @JsonPropertyDescription("Whether this client is enabled")
    public Boolean getEnabled() {
        return this.mapper.get(ENABLED_FIELD);
    }

    public void setEnabled(Boolean enabled) {
        this.mapper.set(ENABLED_FIELD, enabled);
    }

    @URL
    @JsonPropertyDescription("URL to the application's homepage that is represented by this client")
    public String getAppUrl() {
        return this.mapper.get(APP_URL_FIELD);
    }

    public void setAppUrl(String appUrl) {
        this.mapper.set(APP_URL_FIELD, appUrl);
    }

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonPropertyDescription("URIs that the browser can redirect to after login")
    public Set<@NotBlank String> getRedirectUris() {
        return this.mapper.get(REDIRECT_URIS_FIELD);
    }

    public void setRedirectUris(Set<String> redirectUris) {
        this.mapper.set(REDIRECT_URIS_FIELD, redirectUris);
    }

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonPropertyDescription("Roles associated with this client")
    public Set<@NotBlank String> getRoles() {
        return this.mapper.get(ROLES_FIELD);
    }

    public void setRoles(Set<String> roles) {
        this.mapper.set(ROLES_FIELD, roles);
    }

    @NotBlank
    public abstract String getProtocol();

    void setProtocol(String protocol) {
        if (!getProtocol().equals(protocol)) {
            throw new IllegalArgumentException();
        }
    }

}
